# Generated by Django 3.0.2 on 2020-04-28 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airlines',
            fields=[
                ('airlines_id', models.AutoField(primary_key=True, serialize=False)),
                ('airlines_name', models.CharField(max_length=100)),
                ('no_of_persons', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='event_places',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_places',
            },
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_type', models.CharField(max_length=100)),
                ('hotel_location', models.IntegerField()),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='resturant',
            fields=[
                ('resturant_id', models.AutoField(primary_key=True, serialize=False)),
                ('resturant_name', models.CharField(max_length=100)),
                ('resturant_location', models.CharField(max_length=100)),
                ('resturant_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'resturant',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('routes_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_stops', models.CharField(max_length=100)),
                ('google_points', models.CharField(max_length=100)),
                ('start_point', models.CharField(max_length=100)),
                ('middle_point', models.CharField(max_length=100)),
                ('End_point', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='vehicles_type',
            fields=[
                ('vehicles_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicles_type',
            },
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.CharField(max_length=100)),
                ('vendor_password', models.CharField(max_length=100)),
                ('vendor_designation', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles')),
            ],
            options={
                'db_table': 'vendor',
            },
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('vehicles_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicles_name', models.CharField(max_length=100)),
                ('vehicles_type', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='train_station',
            fields=[
                ('train_station_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_station_name', models.CharField(max_length=100)),
                ('no_of_persons', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('routes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.routes')),
            ],
            options={
                'db_table': 'train_station',
            },
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('stops', models.CharField(max_length=100)),
                ('no_of_persons', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('routes_id', models.IntegerField()),
                ('train_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.train_station')),
            ],
            options={
                'db_table': 'train',
            },
        ),
        migrations.CreateModel(
            name='total_price',
            fields=[
                ('total_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=None)),
                ('date', models.CharField(max_length=100)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.hotel')),
                ('resturant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.resturant')),
            ],
            options={
                'db_table': 'total_price',
            },
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_seats', models.IntegerField()),
                ('resturant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.resturant')),
            ],
            options={
                'db_table': 'table',
            },
        ),
        migrations.AddField(
            model_name='routes',
            name='vehicles_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.vehicles'),
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_price', models.CharField(max_length=100)),
                ('no_of_persons', models.IntegerField()),
                ('no_of_rooms', models.IntegerField(default=0)),
                ('discount_rates', models.IntegerField(default=0)),
                ('room_category', models.CharField(max_length=100)),
                ('normal', models.CharField(max_length=100)),
                ('pent_house', models.CharField(max_length=100)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.hotel')),
                ('room_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='res.room_type')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='rikshaw',
            fields=[
                ('rikshaw_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_no', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('routes_id', models.IntegerField()),
                ('duration', models.CharField(max_length=100)),
                ('vehicles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.vehicles')),
            ],
            options={
                'db_table': 'rikshaw',
            },
        ),
        migrations.CreateModel(
            name='resturant_reservations',
            fields=[
                ('restres_id', models.AutoField(primary_key=True, serialize=False)),
                ('resturant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.resturant')),
                ('total_price_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.total_price')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.User')),
            ],
            options={
                'db_table': 'resturant_reservations',
            },
        ),
        migrations.AddField(
            model_name='resturant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.User'),
        ),
        migrations.CreateModel(
            name='resorts',
            fields=[
                ('resort_id', models.AutoField(primary_key=True, serialize=False)),
                ('resort_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.User')),
            ],
            options={
                'db_table': 'resorts',
            },
        ),
        migrations.CreateModel(
            name='makeMyTrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('tripprice', models.IntegerField()),
                ('trip_duration', models.CharField(max_length=100)),
                ('trip_facilities', models.CharField(max_length=100)),
                ('airlines_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.airlines')),
                ('event_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.event_places')),
                ('hotel_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.hotel')),
                ('resort_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.resorts')),
                ('resturant_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.resturant')),
                ('routes_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.routes')),
                ('train_station_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.train_station')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.User')),
                ('vehicles_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.vehicles')),
            ],
            options={
                'db_table': 'makeMyTrip',
            },
        ),
        migrations.CreateModel(
            name='hotel_room',
            fields=[
                ('hotel_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.hotel')),
            ],
            options={
                'db_table': 'hotel_room',
            },
        ),
        migrations.CreateModel(
            name='hotel_reservations',
            fields=[
                ('hotelres_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.CharField(max_length=10)),
                ('check_out', models.CharField(max_length=10)),
                ('day_arrival', models.DateField()),
                ('time_duration', models.CharField(max_length=20)),
                ('total_amount', models.FloatField(default=0.0)),
                ('room_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.room')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.User')),
            ],
            options={
                'db_table': 'hotel_reservations',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.User'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='res.vendor'),
        ),
        migrations.AddField(
            model_name='event_places',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='res.vendor'),
        ),
        migrations.CreateModel(
            name='bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('model_no', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('routes_id', models.IntegerField()),
                ('vehicles_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.vehicles')),
            ],
            options={
                'db_table': 'bus',
            },
        ),
        migrations.CreateModel(
            name='amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField()),
                ('roof_available', models.BooleanField(default=False)),
                ('hotWater_available', models.BooleanField(default=False)),
                ('private_parking_available', models.BooleanField(default=False)),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.room')),
            ],
            options={
                'db_table': 'amenity',
            },
        ),
        migrations.CreateModel(
            name='airplanes',
            fields=[
                ('airplanes_id', models.AutoField(primary_key=True, serialize=False)),
                ('airplanes_name', models.CharField(max_length=100)),
                ('no_of_persons', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('starting_pt', models.CharField(max_length=100)),
                ('end_pt', models.CharField(max_length=100)),
                ('airlines_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.airlines')),
            ],
            options={
                'db_table': 'airplanes',
            },
        ),
        migrations.AddField(
            model_name='airlines',
            name='routes_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.routes'),
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.CharField(max_length=100)),
                ('admin_password', models.CharField(max_length=100)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
