# Generated by Django 3.0.2 on 2020-03-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_reservations',
            name='total_price_id',
        ),
    ]
