# Generated by Django 3.0.2 on 2020-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0002_remove_hotel_reservations_total_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel_reservations',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
