# Generated by Django 3.0.2 on 2020-03-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_hotel_reservations_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_reservations',
            old_name='day',
            new_name='day_arrival',
        ),
    ]
