# Generated by Django 3.0.2 on 2020-03-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0004_auto_20200307_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_places',
            name='trip_id',
        ),
    ]
