# Generated by Django 3.0.2 on 2020-03-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0006_auto_20200314_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='trip_id',
        ),
    ]
