# Generated by Django 3.0.2 on 2020-03-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_remove_vehicles_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.Roles'),
        ),
    ]
