# Generated by Django 3.0.2 on 2020-03-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0008_auto_20200326_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles_type',
            fields=[
                ('vehicles_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicles_type',
            },
        ),
    ]
