# Generated by Django 3.0.2 on 2020-03-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_auto_20200329_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_reservations',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.Roles'),
        ),
    ]
