# Generated by Django 3.0.2 on 2020-04-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_auto_20200330_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_types',
            name='deluxe',
        ),
        migrations.RemoveField(
            model_name='room_types',
            name='suite',
        ),
    ]
