# Generated by Django 3.0.2 on 2020-04-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_auto_20200402_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room_types',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='rooms_id',
            new_name='rooms',
        ),
        migrations.AlterModelTable(
            name='amenity',
            table='amenity',
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
