# Generated by Django 3.0.2 on 2020-04-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0013_auto_20200402_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('room_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'room_type',
            },
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_id',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='res.room_type'),
        ),
    ]
