# Generated by Django 3.0.2 on 2020-04-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0015_room_no_of_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel_room',
            fields=[
                ('hotel_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='res.hotel')),
            ],
            options={
                'db_table': 'hotel_room',
            },
        ),
    ]
