# Generated by Django 3.0.2 on 2020-04-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0016_hotel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel_reservations',
            name='hotel_name',
        ),
        migrations.AddField(
            model_name='hotel_reservations',
            name='room_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='res.room'),
        ),
    ]
