# Generated by Django 3.0.2 on 2020-04-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0017_auto_20200409_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicles_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='res.vehicles_type'),
        ),
    ]
