# Generated by Django 3.0.2 on 2020-04-14 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0018_auto_20200412_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='res_table',
            fields=[
                ('res_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'res_table',
            },
        ),
        migrations.DeleteModel(
            name='table',
        ),
        migrations.AddField(
            model_name='resturant',
            name='res_table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='res.res_table'),
        ),
    ]
