# Generated by Django 3.0.2 on 2020-04-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0019_auto_20200415_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res_table',
            name='no_of_seats',
            field=models.CharField(max_length=100),
        ),
    ]
